'use client';
import { useState } from 'react';
import { getApiBase } from '../../../lib/apiBase';
import { useTranslation } from '../../../lib/i18n/useTranslation';

const C={navy:'#0D3781',blue:'#1565C0',green:'#4CAF50',greenDk:'#388E3C',ink:'#0D1B2A',muted:'#64748B',border:'#E2E8F0',soft:'#F8FAFC',danger:'#DC2626',warning:'#F59E0B',shadow:'0 2px 8px rgba(13,55,129,0.06)'};
const ACCOUNTS={client:{email:'test@evercleanapp.com',password:'password',role:'CLIENT'},pro:{email:'evercleanpro@evercleanapp.com',password:'password',role:'PROFESSIONAL'},admin:{email:'notifications@evercleanapp.com',password:'password',role:'ADMIN'}};

type Result={name:string;status:'ok'|'error'|'loading';data:any;time:string};
function tomorrow10(){const d=new Date();d.setDate(d.getDate()+1);d.setHours(10,0,0,0);return d.toISOString();}
async function readJson(res:Response){const txt=await res.text();try{return txt?JSON.parse(txt):{};}catch{return {raw:txt};}}

export default function AdminTestSuite(){
  const { t }=useTranslation();
  const [clientToken,setClientToken]=useState<any>(null),[proToken,setProToken]=useState<any>(null),[adminToken,setAdminToken]=useState<any>(null);
  const [bookingId,setBookingId]=useState(''); const [results,setResults]=useState<Record<string,Result>>({}); const [last,setLast]=useState('');
  function put(k:string,status:Result['status'],name:string,data:any){setResults(r=>({...r,[k]:{name,status,data,time:new Date().toLocaleString()}}));setLast(name+' - '+status.toUpperCase());}
  async function call(k:string,name:string,path:string,token?:string,body?:any,method?:string){put(k,'loading',name,{});try{const res=await fetch(getApiBase()+path,{method:method||(body?'POST':'GET'),headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined});const data=await readJson(res);put(k,res.ok?'ok':'error',name,{status:res.status,...data});return {ok:res.ok,data};}catch(e:any){put(k,'error',name,{error:e.message});return {ok:false,data:{}};}}
  async function login(kind:'client'|'pro'|'admin'){const a=ACCOUNTS[kind];const r=await call('auth','Login '+a.role,'/auth/login',undefined,{email:a.email,password:a.password});const token=r.data.token||r.data.accessToken;if(kind==='client')setClientToken({token,...a});if(kind==='pro')setProToken({token,...a});if(kind==='admin')setAdminToken({token,...a});return token;}
  async function createBooking(tokenOverride?:string){if(bookingId&&!tokenOverride){put('booking','ok','Create Test Booking',{bookingId,message:'Booking already exists. Continuing with current test booking.'});return bookingId;}let token=tokenOverride||clientToken?.token;if(!token)token=await login('client');if(!token)return put('booking','error','Create Test Booking',{error:'Login as Client first'});const r=await call('booking','Create Test Booking','/bookings',token,{service_type:'HOUSE_CLEANING',state:'NJ',city:'Elizabeth',address:'227 Magnolia Avenue',zip_code:'07206',sqft:900,bedrooms:2,bathrooms:1,kitchens:1,frequency:'ONE_TIME',scheduledAt:tomorrow10(),final_estimated_price:144});const id=r.data.id||r.data.booking?.id||r.data.data?.id;if(id)setBookingId(id);return id;}
  const needBooking=(section='messages')=>bookingId?false:(put(section,'error','Missing booking',{error:'Create booking first or press Immediate Correction'}),true);
  async function autoFixFlow(){put('autofix','loading','Immediate Correction',{});let ct=clientToken?.token,pt=proToken?.token,at=adminToken?.token;if(!ct)ct=await login('client');if(!pt)pt=await login('pro');if(!at)at=await login('admin');let id=bookingId;if(!id&&ct)id=await createBooking(ct);if(!id){put('autofix','error','Immediate Correction',{error:'Could not create booking'});return;}await call('autofix','Check Available Jobs','/bookings/available',pt);await call('autofix','Claim Job','/bookings/'+id+'/claim',pt,{scheduledAt:tomorrow10(),hourlyRate:18});await call('autofix','Send ETA','/bookings/'+id+'/eta',pt,{eta_minutes:15,eta_message:'En camino! Llego en 15 minutos.',pro_lat:40.6636,pro_lng:-74.2107});setResults(r=>({...r,eta:{name:'ETA Ready',status:'ok',time:new Date().toLocaleString(),data:{bookingId:id,eta_minutes:15,eta_message:'En camino! Llego en 15 minutos.',maps_url:'Google Maps URL is returned by backend when available'}}}));await call('autofix','Send Test Message','/bookings/'+id+'/messages',pt,{content:'Hola! Soy tu profesional de EverClean. Confirmo tu servicio para manana. Estoy listo!'});put('autofix','ok','Immediate Correction',{bookingId:id,message:'Flow ready. Continue testing without losing context.'});}
  const card={background:'#fff',border:'1px solid '+C.border,borderRadius:14,boxShadow:C.shadow,padding:20,minWidth:0};
  const Btn=({children,onClick,disabled=false}:{children:any;onClick:any;disabled?:boolean})=><button onClick={onClick} disabled={disabled} style={{border:0,borderRadius:10,background:disabled?C.muted:C.navy,color:'#fff',padding:'10px 14px',fontSize:12,fontWeight:800,cursor:disabled?'not-allowed':'pointer',minHeight:38}}>{children}</button>;
  const Box=({id}:{id:string})=>{const r=results[id];return <pre className="test-result" style={{margin:'12px 0 0',whiteSpace:'pre-wrap',overflow:'auto',maxHeight:230,fontSize:11,background:C.soft,border:'1px solid '+(r?.status==='ok'?C.green:r?.status==='error'?C.danger:C.warning),borderRadius:10,padding:12,color:C.ink}}>{r?JSON.stringify({status:r.status,name:r.name,time:r.time,response:r.data},null,2):'Pending'}</pre>};
  return <div style={{maxWidth:1380,margin:'0 auto',fontFamily:"'Inter',system-ui,sans-serif"}}><style>{`.test-summary{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px;margin-bottom:16px}.test-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;align-items:start}.test-card{min-height:255px}.test-card h3{margin:0 0 12px;font-size:15px;font-weight:800;color:#0D1B2A}.test-result{box-sizing:border-box;width:100%;word-break:break-word}.test-actions{display:flex;gap:8px;flex-wrap:wrap}.test-autofix{display:flex;align-items:center;justify-content:space-between;gap:14px;margin:0 0 16px;padding:16px 18px;border-radius:14px;background:#fff;border:1px solid #E2E8F0;box-shadow:0 2px 8px rgba(13,55,129,.06)}@media(max-width:1050px){.test-summary,.test-grid{grid-template-columns:1fr}.test-card{min-height:auto}}`}</style>
    <div style={{background:'#FEF3C7',border:'1px solid #F59E0B',borderRadius:12,padding:'12px 16px',fontSize:13,fontWeight:900,color:'#92400E',marginBottom:18}}>{t('admin.test.warning')}</div>
    <h1 style={{margin:'0 0 14px',color:C.ink}}>{t('admin.test.title')}</h1>
    <div className="test-summary">{[['Client token',clientToken],['Pro token',proToken],['Admin token',adminToken],['Booking ID',bookingId||'not created'],['Last test',last||'-']].map(x=><div key={x[0] as string} style={card}><div style={{fontSize:11,color:C.muted,fontWeight:800}}>{x[0]}</div><div style={{fontSize:13,fontWeight:900,color:C.ink,marginTop:6,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{typeof x[1]==='object'&&x[1]?'YES':x[1]||'NO'}</div></div>)}</div>
    <div className="test-autofix"><div><div style={{fontSize:15,fontWeight:900,color:C.ink}}>Immediate Correction</div><div style={{fontSize:12,color:C.muted,marginTop:3}}>Runs missing logins, creates a booking when needed, claims it, sends ETA, and sends a test message.</div></div><Btn onClick={autoFixFlow}>Run Immediate Correction</Btn></div><Box id="autofix" />
    <div className="test-grid">
      <section className="test-card" style={card}><h3>Auth Tests</h3><div className="test-actions"><Btn onClick={()=>login('client')}>Login as Client</Btn><Btn onClick={()=>login('pro')}>Login as Pro</Btn><Btn onClick={()=>login('admin')}>Login as Admin</Btn></div><Box id="auth"/></section>
      <section className="test-card" style={card}><h3>Booking Flow Test</h3><div className="test-actions"><Btn onClick={createBooking}>Create Test Booking</Btn><Btn onClick={()=>call('booking','Check Available Jobs','/bookings/available',proToken?.token)}>Check Available Jobs</Btn><Btn onClick={()=>bookingId&&call('booking','Claim Job','/bookings/'+bookingId+'/claim',proToken?.token,{scheduledAt:tomorrow10(),hourlyRate:18})}>Claim Job</Btn></div><Box id="booking"/></section>
      <section className="test-card" style={card}><h3>Communication Tests</h3><div className="test-actions"><Btn onClick={()=>!needBooking('messages')&&call('messages','Pro to Client','/bookings/'+bookingId+'/messages',proToken?.token,{content:'Hola! Soy tu profesional de EverClean. Confirmo tu servicio para manana. Estoy listo!'})}>Send Message Pro</Btn><Btn onClick={()=>!needBooking('messages')&&call('messages','Client to Pro','/bookings/'+bookingId+'/messages',clientToken?.token,{content:'Perfecto! Te espero a las 10am. El codigo de acceso es el 1234.'})}>Send Message Client</Btn><Btn onClick={()=>call('messages','Unread Pro','/messages/unread',proToken?.token)}>Unread Pro</Btn><Btn onClick={()=>!needBooking('messages')&&call('messages','All Messages','/bookings/'+bookingId+'/messages',proToken?.token)}>All Messages</Btn></div><Box id="messages"/></section>
      <section className="test-card" style={card}><h3>ETA and Navigation Test</h3><div className="test-actions"><Btn onClick={()=>!needBooking('messages')&&call('eta','Send ETA','/bookings/'+bookingId+'/eta',proToken?.token,{eta_minutes:15,eta_message:'En camino! Llego en 15 minutos.',pro_lat:40.6636,pro_lng:-74.2107})}>Send ETA</Btn><Btn onClick={()=>!needBooking('messages')&&call('eta','Get ETA','/bookings/'+bookingId+'/eta',clientToken?.token)}>Get ETA</Btn></div><Box id="eta"/></section>
      <section className="test-card" style={card}><h3>Service Completion Test</h3><div className="test-actions"><Btn onClick={()=>!needBooking('messages')&&call('completion','Check In','/bookings/'+bookingId+'/checkin',proToken?.token,{})}>Check In</Btn><Btn onClick={()=>!needBooking('messages')&&call('completion','Complete Service','/bookings/'+bookingId+'/checkout',proToken?.token,{})}>Complete Service</Btn></div><Box id="completion"/></section>
      <section className="test-card" style={card}><h3>Address Autocomplete Test</h3><Btn onClick={()=>call('address','Autocomplete','/address-suggestions?input=11+College+NJ')}>Test Autocomplete</Btn><Box id="address"/></section>
      <section className="test-card" style={card}><h3>Notification Tests</h3><div className="test-actions"><Btn onClick={()=>call('notifications','Test Email','/webhooks/n8n',undefined,{event_type:'TEST_EMAIL',source:'test_dashboard',payload:{message:'Test email from EverClean admin dashboard',to:'notifications@evercleanapp.com'},severity:'LOW'})}>Test Email</Btn><Btn onClick={()=>bookingId?call('notifications','Test SMS Hub','/bookings/'+bookingId+'/messages',adminToken?.token,{content:'Admin SMS hub test'}):put('notifications','error','Test SMS Hub',{error:'Create booking first'})}>Test SMS Hub</Btn></div><Box id="notifications"/></section>
    </div>
  </div>;
}
